services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: 'minio server /data --console-address ":9001"'
  postgres:
    image: postgres:17.5-alpine
    shm_size: 128mb
    volumes:
      - ./src/main/resources/init-db-pg.sh:/docker-entrypoint-initdb.d/01-init-db.sh
      - ./src/main/resources/schema.sql:/schema.sql
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"