CREATE TABLE IF NOT EXISTS account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_key VARCHAR(72) NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS url (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    originalFilename VARCHAR(48),
    url_path VARCHAR(32),
    mime_type ENUM('application/json', 'text/plain', 'application/pdf', 'application/octet-stream'),
    account_id INTEGER,
    FOREIGN KEY (account_id) REFERENCES account (id)
);