name: My custom setup Spring project
description: Setup Spring project with JDK 21 and Gradle
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' }}
    - name: Set environment variables
      run: |
        echo "AWS_ACCESS_KEY_ID=minioadmin" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=minioadmin" >> $GITHUB_ENV
        echo "AWS_ENDPOINT=http://localhost:9000" >> $GITHUB_ENV
        echo "AWS_REGION=eu-west-1" >> $GITHUB_ENV
    - name: Setup local S3
      run: |
        docker run --name minio1 --rm -p 9000:9000 -p 9001:9001 -d minio/minio server /data --console-address ":9001"
        sleep 3
        docker exec minio1 mc alias s local $AWS_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
        docker exec minio1 mc mb -p local/shorturl-test
