name: Build and store artifact
on:
  push:
    branches:
      - main
      - dev
      - frontend
    paths:
      - 'src/**'
      - '*.kts'
      - Dockerfile
      - .github/**
      - 'frontend/**'
env:
  IMAGE_NAME: temp-files-hoster
  PRIVATE_IMAGE_NAME: my-files-hoster
  REGISTRY: ghcr.io
jobs:
  build-private:
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - uses: ./.github/workflows/frontend-setup.yml
        with:
          working-directory: ./frontend
      - run: pnpm install
        working-directory: ./frontend
      - name: Build public frontend
        run: NEXT_TELEMETRY_DISABLED=1 pnpm build
      - name: Copy output frontend to backend
        run: |
          mkdir -p ./src/main/resources/public
          cp -a ./frontend/out/* ./src/main/resources/public
      - uses: ./.github/workflows/backend-setup.yml
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Build image
        run: |
          docker build -t $PRIVATE_IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" --label "org.opencontainers.image.visibility=private" .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          PRIVATE_IMAGE_ID="$REGISTRY/${{ github.repository_owner }}/$PRIVATE_IMAGE_NAME"
          PRIVATE_IMAGE_ID=$(echo $PRIVATE_IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [[ "$VERSION" == "main" ]] && VERSION=latest

          docker tag $PRIVATE_IMAGE_NAME $PRIVATE_IMAGE_ID:$VERSION
          docker push $PRIVATE_IMAGE_ID:$VERSION

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/frontend-setup.yml
        with:
          working-directory: ./frontend
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - run: pnpm install
      - name: Build public frontend
        run: NEXT_TELEMETRY_DISABLED=1 pnpm build
      - name: Upload frontend output
        uses: actions/upload-artifact@v4
        with:
          name: frontend-nextjs
          path: |
            ./frontend/out/
  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/backend-setup.yml
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend-nextjs
          path: ./src/main/resources/public
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact'
          path: |
            ./build/libs/shorturl-*.jar
            !./build/libs/shorturl-*-plain.jar
          compression-level: 0
      - name: Build image
        run: |
          docker build -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}" .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID="$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME"

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [[ "$VERSION" == "main" ]] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
