on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: The directory where the frontend project is located.
jobs:
  setup-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: ${{ inputs.working-directory }}
      - name: Setup Next cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/${{ inputs.working-directory }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
