name: Build and store artifact
on:
  push:
    branches: [ docker-ci ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: liberica
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'artifact'
          path: ./build/libs/shorturl-*!(-plain).jar
          compression-level: 0